### ISSUE TITLE
Side Menu Children Titles Are not visible enough

### ISSUE THREAD

**Issue by qloridant** [etalab/vuepress-theme-gouv-fr#1]
In the side menu, it is difficult to distinguish a children and its sub titles
Solutions :  Another color, more space ... ?

**Comment by AntoineAugusti** [comment]
Done in https://github.com/etalab/vuepress-theme-gouv-fr/commit/8e93af0e32210d27a8361e63e1c13d8ec9f0a903.

Before
![](https://puu.sh/DF1qG/340852bd9f.png)

After
![](https://puu.sh/DF1nc/4586b62ea9.png)

**Comment by AntoineAugusti** [comment]
Available from 0.4.2
