### ISSUE TITLE
Set layout to full page ?

### ISSUE THREAD

**Issue by qloridant** [etalab/vuepress-theme-gouv-fr#2]
Would it be better to set the layout of the page to full page ?

**Actual :** There is not enough space for the table
![not_full_page](https://user-images.githubusercontent.com/14170613/59497438-c8b2ab80-8e93-11e9-970c-3130c96d2330.png)

**Expected :** Enough space
![fullpage](https://user-images.githubusercontent.com/14170613/59497398-af116400-8e93-11e9-86d3-29515b57c796.png)

**Comment by AntoineAugusti** [comment]
Done in https://github.com/etalab/vuepress-theme-gouv-fr/commit/5cf7c8f3f2e0ae2dadc6e4881e2ac74aad6ce961 and available from `0.6.0`.

You can follow the documentation https://vuepress-gouv-fr-demo.eig-forever.org/configuration.html

**Comment by AntoineAugusti** [comment]
It's better to have a narrow layout by default. It makes reading easier, but sometimes, especially for code / chart documentation, it's easier to read on a large screen.

An opt-in class for specific pages seems like a good idea

**Comment by jbledevehat** [comment]
Yes, I agree with @AntoineAugusti

**Comment by qloridant** [comment]
Thanks for the commit and explanation ! Will use it for code documentation only.
