### ISSUE TITLE
Can't get the full page layout

### ISSUE THREAD

**Issue by qloridant** [etalab/vuepress-theme-gouv-fr#4]
I wrote in a page : 

```
---
pageClass: full_page
---

# Modèle de données

### Navire

- Clé primaire : `id_nav_flotteur`
```

but I still have a narrow view. Do I need to change something else ?

**Comment by AntoineAugusti** [comment]
Not sure how I broke this. Do you remember seeing it work before?

Anyway, https://github.com/etalab/vuepress-theme-gouv-fr/commit/43ae2e58870033250a595aedfef0ad45dc85730a fixes it.

Upgrade to 0.7.1 and it should do the trick.

**Comment by qloridant** [comment]
Never saw it work ! 
Now it works. Thanks Antoine
